/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SubmitReviewRouteImport } from './routes/submit.review'
import { Route as SubmitProjectTypeRouteImport } from './routes/submit.project-type'
import { Route as SubmitDetailsRouteImport } from './routes/submit.details'
import { Route as SubmitConfirmationRouteImport } from './routes/submit.confirmation'
import { Route as SubmitBusinessUnitRouteImport } from './routes/submit.business-unit'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminProjectTypesRouteImport } from './routes/admin/project-types'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminBusinessUnitsRouteImport } from './routes/admin/business-units'
import { Route as AdminFormPreviewRouteImport } from './routes/admin/FormPreview'
import { Route as AdminCreateUserModalRouteImport } from './routes/admin/CreateUserModal'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SubmitReviewRoute = SubmitReviewRouteImport.update({
  id: '/submit/review',
  path: '/submit/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitProjectTypeRoute = SubmitProjectTypeRouteImport.update({
  id: '/submit/project-type',
  path: '/submit/project-type',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitDetailsRoute = SubmitDetailsRouteImport.update({
  id: '/submit/details',
  path: '/submit/details',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitConfirmationRoute = SubmitConfirmationRouteImport.update({
  id: '/submit/confirmation',
  path: '/submit/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitBusinessUnitRoute = SubmitBusinessUnitRouteImport.update({
  id: '/submit/business-unit',
  path: '/submit/business-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectTypesRoute = AdminProjectTypesRouteImport.update({
  id: '/project-types',
  path: '/project-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessUnitsRoute = AdminBusinessUnitsRouteImport.update({
  id: '/business-units',
  path: '/business-units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormPreviewRoute = AdminFormPreviewRouteImport.update({
  id: '/FormPreview',
  path: '/FormPreview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateUserModalRoute = AdminCreateUserModalRouteImport.update({
  id: '/CreateUserModal',
  path: '/CreateUserModal',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/CreateUserModal': typeof AdminCreateUserModalRoute
  '/admin/FormPreview': typeof AdminFormPreviewRoute
  '/admin/business-units': typeof AdminBusinessUnitsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/project-types': typeof AdminProjectTypesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/submit/business-unit': typeof SubmitBusinessUnitRoute
  '/submit/confirmation': typeof SubmitConfirmationRoute
  '/submit/details': typeof SubmitDetailsRoute
  '/submit/project-type': typeof SubmitProjectTypeRoute
  '/submit/review': typeof SubmitReviewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/CreateUserModal': typeof AdminCreateUserModalRoute
  '/admin/FormPreview': typeof AdminFormPreviewRoute
  '/admin/business-units': typeof AdminBusinessUnitsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/project-types': typeof AdminProjectTypesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/submit/business-unit': typeof SubmitBusinessUnitRoute
  '/submit/confirmation': typeof SubmitConfirmationRoute
  '/submit/details': typeof SubmitDetailsRoute
  '/submit/project-type': typeof SubmitProjectTypeRoute
  '/submit/review': typeof SubmitReviewRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/CreateUserModal': typeof AdminCreateUserModalRoute
  '/admin/FormPreview': typeof AdminFormPreviewRoute
  '/admin/business-units': typeof AdminBusinessUnitsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/project-types': typeof AdminProjectTypesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/submit/business-unit': typeof SubmitBusinessUnitRoute
  '/submit/confirmation': typeof SubmitConfirmationRoute
  '/submit/details': typeof SubmitDetailsRoute
  '/submit/project-type': typeof SubmitProjectTypeRoute
  '/submit/review': typeof SubmitReviewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/CreateUserModal'
    | '/admin/FormPreview'
    | '/admin/business-units'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/project-types'
    | '/admin/submissions'
    | '/admin/users'
    | '/submit/business-unit'
    | '/submit/confirmation'
    | '/submit/details'
    | '/submit/project-type'
    | '/submit/review'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/CreateUserModal'
    | '/admin/FormPreview'
    | '/admin/business-units'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/project-types'
    | '/admin/submissions'
    | '/admin/users'
    | '/submit/business-unit'
    | '/submit/confirmation'
    | '/submit/details'
    | '/submit/project-type'
    | '/submit/review'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/CreateUserModal'
    | '/admin/FormPreview'
    | '/admin/business-units'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/project-types'
    | '/admin/submissions'
    | '/admin/users'
    | '/submit/business-unit'
    | '/submit/confirmation'
    | '/submit/details'
    | '/submit/project-type'
    | '/submit/review'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubmitBusinessUnitRoute: typeof SubmitBusinessUnitRoute
  SubmitConfirmationRoute: typeof SubmitConfirmationRoute
  SubmitDetailsRoute: typeof SubmitDetailsRoute
  SubmitProjectTypeRoute: typeof SubmitProjectTypeRoute
  SubmitReviewRoute: typeof SubmitReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/submit/review': {
      id: '/submit/review'
      path: '/submit/review'
      fullPath: '/submit/review'
      preLoaderRoute: typeof SubmitReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/project-type': {
      id: '/submit/project-type'
      path: '/submit/project-type'
      fullPath: '/submit/project-type'
      preLoaderRoute: typeof SubmitProjectTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/details': {
      id: '/submit/details'
      path: '/submit/details'
      fullPath: '/submit/details'
      preLoaderRoute: typeof SubmitDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/confirmation': {
      id: '/submit/confirmation'
      path: '/submit/confirmation'
      fullPath: '/submit/confirmation'
      preLoaderRoute: typeof SubmitConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/business-unit': {
      id: '/submit/business-unit'
      path: '/submit/business-unit'
      fullPath: '/submit/business-unit'
      preLoaderRoute: typeof SubmitBusinessUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/project-types': {
      id: '/admin/project-types'
      path: '/project-types'
      fullPath: '/admin/project-types'
      preLoaderRoute: typeof AdminProjectTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business-units': {
      id: '/admin/business-units'
      path: '/business-units'
      fullPath: '/admin/business-units'
      preLoaderRoute: typeof AdminBusinessUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/FormPreview': {
      id: '/admin/FormPreview'
      path: '/FormPreview'
      fullPath: '/admin/FormPreview'
      preLoaderRoute: typeof AdminFormPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/CreateUserModal': {
      id: '/admin/CreateUserModal'
      path: '/CreateUserModal'
      fullPath: '/admin/CreateUserModal'
      preLoaderRoute: typeof AdminCreateUserModalRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCreateUserModalRoute: typeof AdminCreateUserModalRoute
  AdminFormPreviewRoute: typeof AdminFormPreviewRoute
  AdminBusinessUnitsRoute: typeof AdminBusinessUnitsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectTypesRoute: typeof AdminProjectTypesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateUserModalRoute: AdminCreateUserModalRoute,
  AdminFormPreviewRoute: AdminFormPreviewRoute,
  AdminBusinessUnitsRoute: AdminBusinessUnitsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectTypesRoute: AdminProjectTypesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SubmitBusinessUnitRoute: SubmitBusinessUnitRoute,
  SubmitConfirmationRoute: SubmitConfirmationRoute,
  SubmitDetailsRoute: SubmitDetailsRoute,
  SubmitProjectTypeRoute: SubmitProjectTypeRoute,
  SubmitReviewRoute: SubmitReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
